---
name: ci
on:
  pull_request:

env:
  NODE_VERSION: 18.7.0
  TERM: xterm

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      #- name: ci/test
      #  uses: ./.github/actions/test
      - name: git status
        run: git status
      - name: npm run i18n-extract
        run: npm run i18n-extract
      - name: git status
        run: git status
